# Generated by Django 2.1.5 on 2021-03-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0009_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
